### ISSUE TITLE
SELECT (NEXT VALUE FOR TestSeq) with RPC Flow and fast-forward scroll option skips sequence items

### ISSUE THREAD

**Issue by vlipovetskii** [r2dbc/r2dbc-mssql#113]
I get next sequence number from MS Sql Server sequence. Code to create sequence in a db is above.
Each call of "SELECT CAST(NEXT VALUE FOR TestSeq AS BIGINT)" should return numbers 1, 2, 3, ...
In fact, it returms 2, 4, 6, ...
Test above reproduces this problem.

2dbc-mssql 0.8.0.RC2
spring-boot-starter-data-r2dbc: 0.1.0.M2

Expected 1, 2, 3, ...
Actual: 2, 4, 6, ...

```kotlin
@Autowired
private lateinit var databaseClient: DatabaseClient

@Test
@Order(1)
fun `give TestSeq RESTART WITH 1 when SELECT CAST(NEXT VALUE FOR TestSeq AS BIGINT) then 1 returned`() {

    /*
    -- DROP SEQUENCE TestSeq
    -- CREATE SEQUENCE TestSeq START WITH 1 INCREMENT BY 1
     */

    databaseClient
            .execute("ALTER SEQUENCE TestSeq RESTART WITH 1")
            .fetch().first().block()

    databaseClient
            .execute("SELECT CAST(NEXT VALUE FOR TestSeq AS BIGINT)")

            .`as`(java.lang.Long::class.java).fetch()

            .first().block() `should equal` 1.toLong()

}
```

The issue is reproduced using the SQL Server driver directly via:
https://github.com/spring-projects/spring-data-r2dbc/issues/221#issuecomment-547314062

P.S. I work with Ms sql sequences using JDBC (JTDS) without any problems.

**Comment by mp911de** [comment]
The issue can be reproduced with the SQL Server JDBC driver, so it's likely to be a SQL Server issue.

The cursored execution flow uses the fast-forward scroll option (`16`) which seems to resonate with something with SQL server. Not sure whether that's a bug or a feature. 
We should change the scroll option to forward-only (`4`) to align with the JDBC driver defaults. 

References:

* spring-projects/spring-data-r2dbc#221
* microsoft/mssql-jdbc#1174

**Comment by vlipovetskii** [comment]
> We should change the scroll option to forward-only (4) to align with the JDBC driver defaults.
How to do it ?

**Comment by mp911de** [comment]
We need to update our code, specifically https://github.com/r2dbc/r2dbc-mssql/blob/master/src/main/java/io/r2dbc/mssql/RpcQueryMessageFlow.java#L451 and other methods using RPC cursor calls.
