### ISSUE TITLE
Provide additional configuration options for hostNameInCertificiate

### ISSUE THREAD

**Issue by lhaatveit** [r2dbc/r2dbc-mssql#138]
## Feature Request

Provide a way to configure the client to accept certificates for all sub-domains under a given root. I believe the only current mechanism for configuring certificate host name acceptance is by using a wildcard in the hostNameInCertificate property of the configuration SPI. However, it will only allow immediate sub domains. (E.g. `*.foo` accepts `bar.foo`, but not `baz.bar.foo`)

#### Is your feature request related to a problem? Please describe

When using Azure SQL you connect to `<tenant>.database.windows.net`. For e.g. JDBC you are asked to use `hostNameInCertificate=*.database.windows.net` in the connection string. The actual certificate host name follows a pattern like `indiasouth1-a.control.database.windows.net` depending on which region you connect to. You may also be routed to a different server, e.g. `c95b106f606b.tr2.indiasouth1-a.worker.database.windows.net`.

#### Describe the solution you'd like

I would like a way to configure a pattern that will accept any domain under a root domain (maybe a regular expression or possibly Ant `**` syntax). Alternatively provide an SPI that allows overriding the certificate host name verification.

#### Describe alternatives you've considered

The only alternative at the moment is to explicitly set the certificate host name. However, I believe a) it may change and b) it won't work with routing.

**Comment by mp911de** [comment]
We [implemented the hostname checking](https://github.com/r2dbc/r2dbc-mssql/blob/master/src/main/java/io/r2dbc/mssql/client/ssl/ExpectedHostnameX509TrustManager.java) along the lines of [how the JDBC driver checks the hostname](https://github.com/microsoft/mssql-jdbc/blob/dev/src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java#L1414-L1459). 

The JDBC driver does not seem to require additional configuration and that indicates that we missed some functionality that is required for a seamless Azure experience. In general, it makes sense to keep functionality similar across drivers.

Right now, a placeholder indicates a mask for only a single segment.

**Comment by mp911de** [comment]
I took a look into the validation and noticed that the server certificate contains subject alternative names that cover `*.database.windows.net` while our `HostNamePredicate` does not check for wildcards in SAN/CN entires. I reclassified this ticket as bug that we should fix.
