### ISSUE TITLE
What is the minimum supported sql-server version?

### ISSUE THREAD

**Issue by rj-hwang** [r2dbc/r2dbc-mssql#139]
What is the minimum supported sql-server version?

**Comment by mp911de** [comment]
Our code is laid out to require SQL Server 2005 (Version 9.0/Yukon). We were only able to run tests with SQL Server 2017 and newer due to the docker setup.

**Comment by rj-hwang** [comment]
Thanks! I run my unit test with SQL Server 2005, it succeed.
