### ISSUE TITLE
Document supported data types

### ISSUE THREAD

**Issue by mp911de** [r2dbc/r2dbc-mssql#18]
Hi, this is a `first-timers-only` issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general `ideal-for-contribution` issues. Thanks!

## Background

We should document which [SQL Server data types](https://docs.microsoft.com/en-us/sql/t-sql/data-types/data-types-transact-sql) are currently supported by this driver to document features/limitations. Any non-documented data type is not supported.

## Problem

Right now, it's not obvious which data types can be used and to which Java types SQL Server types map to.

## Solution

Supported data types can be found by checking for `Codec` implementations in the [`io.r2dbc.mssql.codec`](https://github.com/r2dbc/r2dbc-mssql/tree/master/src/main/java/io/r2dbc/mssql/codec) package. Supported data types can be a table (matrix) between the SQL Server data type  (e.g. `VARCHAR`) and to which Java type it maps to (e.g. `java.lang.String`, based on [`StringCodec`](https://github.com/r2dbc/r2dbc-mssql/blob/master/src/main/java/io/r2dbc/mssql/codec/StringCodec.java#L47-L58).

The table with the type mapping should be added to our [`README.md`](https://github.com/r2dbc/r2dbc-mssql/blob/master/README.md).

## Steps to fix

- [x] Claim this issue with a comment below and ask any clarifying questions you need.
- [ ] Set up a repository locally following the [Contributing Guidelines](https://github.com/r2dbc/r2dbc-mssql/blob/master/CONTRIBUTING.adoc).
- [ ] Try to fix the issue following the steps above.
- [ ] Commit your changes and start a pull request.

## Deliverables

- [ ] Updated `README.md` containing a section which SQL Server data types are currently supported by this driver.

**Comment by rifatdover** [comment]
Assign on me :)

**Comment by mp911de** [comment]
Consider it claimed. Let us know if you need any assistance.

**Comment by rifatdover** [comment]
https://github.com/r2dbc/r2dbc-mssql/blob/c0a2ee0dab855f47241412df41f38e79bcfa8778/src/main/java/io/r2dbc/mssql/codec/StringCodec.java#L54

@mp911de I think we should add ``` SqlServerType.TEXT,  SqlServerType.NTEXT, and SqlServerType.NVARCHARMAX ``` types here. Am I wrong?

**Comment by rifatdover** [comment]
Did you not add these values because they are not supported or will be removed? @mp911de 
Are we going to add them to documentation?

**Comment by mp911de** [comment]
Thanks for reaching out. Big character data types are partially length-prefixed (see #28) and not yet supported. We should leave these out of the docs (not documented means unsupported) and we will document these once we have proper support for PLP types.
