### ISSUE TITLE
Support for different schema

### ISSUE THREAD

**Issue by danielfosse** [r2dbc/r2dbc-mssql#187]
In a database instance you can have multiple schemas, so you could have a table called Test.product and another called Foo.product. JPA and hibernate have support for schemas, so it would be great to have that here.

**Comment by mp911de** [comment]
Not sure I understand what you're asking for. `Connection.createStatement(sql)` allows you specifying arbitrary SQL. So you can easily create a query `SELECT * FROM dbo.foo` and `SELECT * FROM otherschema.dbo.foo`.

**Comment by danielfosse** [comment]
I want to override the default schema in spring application properties so i can use @Table(value="product") in my entity class.
In the configuration it would say something like properties.schema: 'Test'.

**Comment by mp911de** [comment]
`@Table` is not part of this driver. You'd rather want to file a ticket in https://github.com/spring-projects/spring-data-r2dbc or specifically look at this StackOverflow question: https://stackoverflow.com/questions/64629463/how-to-specify-table-schema-in-spring-data-jdbc
