### ISSUE TITLE
Strip ROWSTAT column from MssqlRowMetadata

### ISSUE THREAD

**Issue by mp911de** [r2dbc/r2dbc-mssql#188]
Cursor fetch synthesizes a `ROWSTAT` column that pollutes the metadata and reports therefore an additional column. We should strip the column from the metadata. The JDBC driver does this depending on whether a server-side cursor was spun up. Since the cursorId is received in a `ReturnValue` token which comes last, we cannot wait for the `ReturnValue`. Instead, we inspect whether the last column is named `ROWSTAT` and remove it if so.

Related to r2dbc/r2dbc-spi/issues#187.

**Comment by chadlwilson** [comment]
Thanks for this. I don't suppose there's a chance of this getting a released backport to `0.8.x` 😅 Trying my luck since `0.9.0` seems a little way off. :-)

**Comment by mp911de** [comment]
This is a minimal change and we can backport it. Can you open a new ticket?

**Comment by chadlwilson** [comment]
Sure, thanks @mp911de - done in #235
