### ISSUE TITLE
Support SQL Server-specific transaction isolation levels by adding setTransactionIsolationLevel(MssqlIsolationLevel) to MssqlConnection

### ISSUE THREAD

**Issue by mp911de** [r2dbc/r2dbc-mssql#19]
Hi, this is a `first-timers-only` issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general `ideal-for-contribution` issues. Thanks!

## Background

SQL server supports more isolation levels than specified in [R2DBC SPI](https://github.com/r2dbc/r2dbc-spi/blob/master/r2dbc-spi/src/main/java/io/r2dbc/spi/IsolationLevel.java#L22).

## Problem

We would like to support `SNAPSHOT` isolation in this driver. R2DBC defines isolation levels in an `enum` which makes extension impossible.

R2DBC SPI declares the following levels:
* `READ_COMMITTED`
* `READ_UNCOMMITTED`
* `REPEATABLE_READ`
* `SERIALIZABLE`

SQL Server supports additionally the [`SNAPSHOT`](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-transaction-isolation-level-transact-sql) level.

## Solution

We need a driver-specific enum that contains all SQL server isolation levels (modelled along the lines of R2DBC's [`IsolationLevel` enum](https://github.com/r2dbc/r2dbc-spi/blob/master/r2dbc-spi/src/main/java/io/r2dbc/spi/IsolationLevel.java#L22)).
 We also need another [`setTransactionIsolationLevel`](https://github.com/r2dbc/r2dbc-mssql/blob/ba8204f6b76a211bef53d4e2ae0da91f7dc99250/src/main/java/io/r2dbc/mssql/MssqlConnection.java#L189) method that allows to set the isolation level through the new enumeration.

## Steps to fix

- [x] Claim this issue with a comment below and ask any clarifying questions you need.
- [ ] Set up a repository locally following the [Contributing Guidelines](https://github.com/r2dbc/r2dbc-mssql/blob/master/CONTRIBUTING.adoc).
- [ ] Try to fix the issue following the steps above.
- [ ] Commit your changes and start a pull request.

## Deliverables

- [ ] Create a `MssqlIsolationLevel` enum.
- [ ] Extend `io.r2dbc.mssql.MssqlConnection` by adding a `setTransactionIsolationLevel(MssqlIsolationLevel)` method.
- [ ] Add a unit test for the new method to [`MssqlConnectionUnitTests`](https://github.com/r2dbc/r2dbc-mssql/blob/95bd738cf11d52f05e1d28e5a3d70cdeb39d89ed/src/test/java/io/r2dbc/mssql/MssqlConnectionUnitTests.java#L237).

**Comment by uaihebert** [comment]
Hey, I would like to claim this. :D

**Comment by mp911de** [comment]
Consider it claimed. Let us know if you need any assistance.

**Comment by uaihebert** [comment]
Nice!

all the tests are passing: https://github.com/r2dbc/r2dbc-mssql/pull/26

I hope I got it correct.

**Comment by mp911de** [comment]
Awesome work. I left a few comments on your pull request.
