### ISSUE TITLE
Can you tell me the url  of Microsoft SQL Server client protocol ? please

### ISSUE THREAD

**Issue by qinarmy-zoro** [r2dbc/r2dbc-mssql#277]
Can you tell me the url  of Microsoft SQL Server client protocol ? please . I couldn't find it.

**Comment by mp911de** [comment]
You can find the protocol documentation at https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-tds/b46a581a-39de-4745-b076-ec4dbb7d13ec

**Comment by qinarmy-zoro** [comment]
thank you,I love you,I found too long time, microsoft document website too big.
