### ISSUE TITLE
Add support for binary types

### ISSUE THREAD

**Issue by mp911de** [r2dbc/r2dbc-mssql#3]
We should add support for `VARBINARY` to support `ByteBuffer`/`byte[]` representations of binary data.

**Comment by uaihebert** [comment]
Hello, I am willing to look into this, but I will need more info. I still new in r2dbc. 

I noticed that we got the enum `SqlServerType`. 

I was able to find this:

```
    VARBINARY(Category.BINARY,          "varbinary"),
    VARBINARYMAX(Category.LONG_BINARY,  "varbinary"),
```

When you say:  " to support `ByteBuffer / byte[]` " it would mean new type on the `SqlServerType`? or create a new `TdsDataType` and include on the `SqlServerType` construtor?

**Comment by uaihebert** [comment]
I just found also the `TypeBuilder`. or should there be the new support added?

**Comment by uaihebert** [comment]
or maybe if you have any material that I should read/practice before going further, it would be good. ( :

**Comment by mp911de** [comment]
Here are a few pointers:

* Protocol documentation (overview): https://msdn.microsoft.com/en-us/library/dd304523.aspx
* Protocol documentation (TDS 7.4, rev25): https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-TDS/[MS-TDS].pdf (see page 26 for data types)

Places that contain already support for `BIGBINARY`/`BIGVARBINARY`:

* `TdsDataType`
* `SqlServerType`
* `TypeBuilder`

Places to change:

* New `ByteArrayCodec`
* New `ByteBufferCodec`
* `DefaultCodecs`, add the new codecs.

I'm not sure regarding the default data type, I suppose it would make the most sense to decode binary types to `byte[]`.

A tip for testing: I used the JDBC driver to set up a test case (create table, insert data, select data) and then use the verbose logging (see https://docs.microsoft.com/en-us/sql/connect/jdbc/tracing-driver-operation?view=sql-server-2017, logger `com.microsoft.sqlserver.jdbc.internals.TDS.DATA`) to intercept the wire protocol. Another possibility is using wireshark or tcpdump.

**Comment by uaihebert** [comment]
hello, I will invest time in this task this week. 

Could you just help me with one more thing? I want to create a local table, what should be the correct column type?

**Comment by mp911de** [comment]
There would be three types:

* BINARY(n)
* VARBINARY(n)
* VARBINARY(MAX) - this one is related to #28. let’s leave this one for later.
