### ISSUE TITLE
Output of generated keys not working for UUID / uniqueidentifier

### ISSUE THREAD

**Issue by stdreyer** [r2dbc/r2dbc-mssql#36]
I am using `UUID` / `uniqueidentifier` primary keys.

```
CREATE TABLE test (
  id UNIQUEIDENTIFIER DEFAULT NEWID(),
  text VARCHAR(255)
)
```

When inserting a new object, I dont get the generated id. `GENERATED_KEYS` is empty.

```
INSERT INTO test (text) VALUES('test') select SCOPE_IDENTITY() AS GENERATED_KEYS;
```
Will return `NULL`.

That is an issue of SQL Server but the workaround would be to use the `OUTPUT` syntax:

```
INSERT INTO test (text) OUTPUT inserted.id VALUES('test');
```

That will actually return something like | id | B5BA707B-872E-4BFC-8A96-97A1D789E74C |

**Comment by essentinal** [comment]
A quick workaround would look like that: https://github.com/essentinal/r2dbc-mssql/commit/d8737eb1e139fbec07c890836e3aa20c4562ebbb

But that isn't a good solution since it relies on `id` being the name of the identifier column.
A good implementation would check the entity type for an annotation like `javax.persistence.Id` or `org.springframework.data.annotation.Id` and than use the db column name in `OUTPUT inserted.xxx`.
But the mssql driver never has any type information available.

**Comment by mp911de** [comment]
Which component applies the workaround when using JDBC? Is it the [JDBC driver](https://github.com/Microsoft/mssql-jdbc) itself? We should not rewrite SQL statements on driver level unless we have to.

I think spring-projects/spring-data-jdbc#125 is an ideal place to leave this remark.

**Comment by essentinal** [comment]
There is no need for a workaround if you use the `OUTPUT` syntax instead of `SELECT SCOPE_IDENTITY()`.

**Comment by mp911de** [comment]
Out of curiosity: Why would someone use `SELECT SCOPE_IDENTITY()` instead of `OUTPUT inserted.*` (or `inserted.(name of column)`) syntax to obtain generated values?

**Comment by mp911de** [comment]
`returnGeneratedKeys(…)` is a hint for drivers to return a variant of generated keys without regard to how tables are seen from an application perspective (tables, entities, plain SQL). For SQL Server, returning generated keys is just a matter of SQL and we want to keep the same level of functionality as JDBC. Closing this ticket without change.

**Comment by franklsm1** [comment]
I am seeing the same issue that @stdreyer mentioned in the initial issue statement. When using spring-data-r2dbc it just passes the insert query through to the r2dbc-mssql dependency. This is where `SELECT SCOPE_IDENTITY() AS GENERATED_KEYS` is appended to the SQL to be ran (in the `GeneratedValues.augmentQuery` method). What is the work around to continue to use the r2dbc-mssql dependency but use the `OUTPUT` syntax?

**Comment by mp911de** [comment]
R2DBC MSSQL aligns on `Statement.returnGeneratedKeys()` with what the JDBC driver does. Keep in mind that you have full control over the SQL statement with the driver when running your own SQL. Some client libraries building on top of R2DBC are more opinionated. The `OUTPUT` clause is applicable in various cases. Using it requires a bit of knowledge about the table structure, so there's nothing we can do in the driver without introducing the risk of damaging the SQL statement.

Here's an example to use the `OUTPUT` syntax:

```sql
CREATE TABLE foo (
    id uniqueidentifier NOT NULL DEFAULT NEWID() ,  
    Name VARCHAR(50)); 
```

```java
MssqlConnection connection = …;

connection.createStatement("INSERT INTO foo (NAME) OUTPUT INSERTED.id, INSERTED.Name VALUES ('Hello')")
    .execute()
    .flatMap(it -> it.map((row, rowMetadata) -> {

            System.out.println(row.get("id"));
            System.out.println(row.get("name"));

            return "";
        })).blockLast();
```

**Comment by essentinal** [comment]
Whatever works with custom statements, `r2dbc-mssql` doesn't return ids with `spring-data-r2dbc` where other drivers do. 

We switched to `r2dbc-postgresql` for that reason and everything works fine.

**Comment by mp911de** [comment]
According to the SQL server team, returning generated values is a limitation on the server-side when using `SCOPE_IDENTITY`. Leaving microsoft/mssql-jdbc#245 as reference.

**Comment by franklsm1** [comment]
That mssql-jdbc issue is referencing an issue when returning multiple generated keys. In this case just like the example in this issue, I am only trying to get back a single generated key and that is returning back as null. I think this is a slightly different issue than the one you referenced.

**Comment by mp911de** [comment]
Thanks, I missed that subtlety.
